### ISSUE TITLE
Tarea Infografía sistemas numéricos

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/infografia-Edwin14459#2]
[Infografía sistemas numéricos Edwin López Santiago.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Edwin14459/files/7126116/Infografia.sistemas.numericos.Edwin.Lopez.Santiago.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación de acuerdo a rúbrica

**Comment by josealfredo79** [comment]
Falta la calificación

**Comment by UrielGB10** [comment]
Compañero te pondrá la calificación de 15% por que te faltaron algunas cosas

**Comment by josealfredo79** [comment]
Bien hecho y revisado
